# Generated by Django 5.2.6 on 2025-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipper",
            fields=[
                ("shipper_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "shipper_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipper_contact_details",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "Shippers",
            },
        ),
    ]
