# Generated by Django 5.2.6 on 2025-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=15, null=True)),
                ("job_title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=50, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=25, null=True)),
                ("country", models.CharField(blank=True, max_length=40, null=True)),
                ("state", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "customer_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("postal_code", models.IntegerField(blank=True, null=True)),
                (
                    "credit_card_type",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("credit_card_number", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Customer",
            },
        ),
    ]
