# Generated by Django 5.2.6 on 2025-09-10 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        ("shippers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                (
                    "vehicle_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("ship_date", models.DateField(blank=True, null=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("ship_mode", models.CharField(blank=True, max_length=25, null=True)),
                ("shipping", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "customer_feedback",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("quarter_number", models.IntegerField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "shipper",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shippers.shipper",
                    ),
                ),
            ],
            options={
                "db_table": "Order",
            },
        ),
    ]
