# Generated by Django 5.2.6 on 2025-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.IntegerField(primary_key=True, serialize=False)),
                ("vehicle_maker", models.CharField(max_length=60)),
                ("vehicle_model", models.CharField(max_length=60)),
                ("vehicle_color", models.CharField(max_length=60)),
                ("vehicle_model_year", models.IntegerField()),
                ("vehicle_price", models.DecimalField(decimal_places=8, max_digits=14)),
            ],
        ),
    ]
