# Generated by Django 5.2.6 on 2025-09-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="Products",
        ),
    ]
